# Generated by Django 2.2.6 on 2019-10-23 10:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=140)),
                ('position', models.CharField(default='CNN Agent', max_length=140)),
                ('description', models.TextField(max_length=1500)),
                ('image', models.ImageField(null=True, upload_to='static/')),
                ('rating', models.PositiveSmallIntegerField()),
                ('mature', models.BooleanField(default=False)),
                ('pricepergb', models.IntegerField(null=True)),
                ('earned', models.IntegerField(null=True)),
                ('developer', models.CharField(default='ATN', max_length=80)),
                ('user', models.ForeignKey(on_delete='SET_NULL', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
