# Generated by Django 2.2.6 on 2019-10-25 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contact Message', 'verbose_name_plural': 'Contact Messages'},
        ),
    ]
